# Generated by Django 2.2.7 on 2020-01-05 22:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpostposting',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 22, 49, 36, 491464, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurantstoryposting',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 4, 22, 49, 36, 491970, tzinfo=utc)),
        ),
    ]
