# Generated by Django 2.2.7 on 2019-12-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='is_student',
            field=models.BooleanField(default=False),
        ),
    ]
