# Generated by Django 2.2.7 on 2019-12-31 03:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantpostposting',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 3, 18, 7, 409373, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='restaurantstoryposting',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 30, 3, 18, 7, 409868, tzinfo=utc)),
        ),
    ]
