# Generated by Django 2.2.7 on 2019-12-04 16:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191204_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantpostposting',
            old_name='initial_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='restaurantstoryposting',
            old_name='initial_quantity',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='restaurantpostposting',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 16, 57, 14, 818167, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='restaurantstoryposting',
            name='expiry_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 3, 16, 57, 14, 818645, tzinfo=utc)),
        ),
    ]
